FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies with legacy peer deps flag
RUN npm install --legacy-peer-deps

# Copy the rest of the application code
COPY . .

# Expose port 3000
EXPOSE 3000

ENV HOSTNAME "0.0.0.0"

# Start the development server
CMD ["npm", "run", "dev"]
